### ISSUE TITLE
ALC 298 (Alienware 15R4 Audio not working)

### ISSUE THREAD

**Issue by rajverma1985** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14#1]
Hey, good day. I was wondering if you could help me out with the audio on Mojave for alienware 15r4.
Im actually using the clover files from alienware 17R4 and everything works except for the audio. I have tried your method mentioned at: 

https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/16

and i followed the instructions at the end of the page of issue 16. 
<<Start of comment>>
"
Ok here are complete instructions and files that work.

    Be sure to use latest FakePCIID kexts including FakePCIID_Intel_HDMI_Audio.kext.
    download and install Codec Commander kext
    download and install ALC298 Alienware package. Install - a) AppleHDA.kext. b) run the AlcFix.
    ALC298 AlienWare.zip

Everything works except external mic. (If you plug in headphones+mic, headphone mic will not detect. However, internal laptop mic works so it's ok.)
"

<<End of comment>>

So the above also doesn't work. I'm using clover to install. I created the bootable using basic createbootmedia method. No method really works :(, Any help would be appreciated. 

Link for my clovers:

https://www.tonymacx86.com/threads/guide-alienware-17-r4-dual-gpu-macos-mojave.263577/ 

The is a guy James, i'm using his Clover files.
My hardware info:

alienware 15r4
proc: i7 8750H
GPU gtx1070
Audio:  Realtek-ALC3266

**Comment by rajverma1985** [comment]
I'm on Mojave (10.14.3), also I just started getting this error now and now its not detecting audio at all.

error:

Kext rejected due to improper filesystem permissions: <OSKext 0x7fbcdf6f45d0 [0x7fffa4b128f0]> { URL = "AppleHDAController.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.driver.AppleHDAController" }
AppleHDAController.kext does not authenticate; omitting.
Kext rejected due to improper filesystem permissions: <OSKext 0x7fbcdf6fb1a0 [0x7fffa4b128f0]> { URL = "IOHDAFamily.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.iokit.IOHDAFamily" }
IOHDAFamily.kext does not authenticate; omitting.
Kext rejected due to improper filesystem permissions: <OSKext 0x7fbcdf6ea6e0 [0x7fffa4b128f0]> { URL = "AppleHDA.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.driver.AppleHDA" }
AppleHDA.kext does not authenticate; omitting.
Invalid signature -67030 for kext <OSKext 0x7fbce09244d0 [0x7fffa4b128f0]> { URL = "NVDAStartupWeb.kext/ -- file:///Library/Extensions/", ID = "com.nvidia.NVDAStartupWeb" }
kxld[com.nvidia.web.GeForceWeb]: The following symbols are unresolved for this kext:
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelShared2::lookupDeviceShmem(unsigned int)
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelSurface2::getSurfaceBuffer(eIOAccelGLBufferType)
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelSurface2::convertGLIndexToBufferIndex(eIOAccelGLBufferType)
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelResource2::requirePageon()
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelResource2::newResourceWithOptions(IOGraphicsAccelerator2*, IOAccelShared2*, eIOAccelResType, unsigned long long, unsigned int, unsigned long long, unsigned long long*)
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelResource2::getClientSharedROPrivate()
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelResource2::getClientSharedRWPrivate()
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelDisplayPipe2::getFramebuffer()
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelDisplayMachine2::getDisplayPipe(unsigned int)
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelDisplayMachine2::getIOFramebuffer(unsigned int)
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelDisplayMachine2::getScanoutSurface(unsigned int)
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelDisplayMachine2::getScanoutResource(unsigned int, unsigned int)
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelDisplayMachine2::getFramebufferCount()
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelDisplayMachine2::isFramebufferActive(unsigned int)
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelDisplayMachine2::getFullScreenSurface(unsigned int)
kxld[com.nvidia.web.GeForceWeb]: 	IOAccelDisplayMachine2::getFramebufferResource(unsigned int, unsigned int)

**Comment by rajverma1985** [comment]
Hey my Os version Mojave 10.14.3

**Comment by insanelydeepak** [comment]
share your clover folder ??

**Comment by rajverma1985** [comment]
> share your clover folder ??

Yes, PFA my clover files.

Also new Update. I removed Mojave and installed High Sierra. Everything works. Except for the Audio mic & location. I have done the steps for audio as well.

[CLOVER.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2825773/CLOVER.zip)

**Comment by insanelydeepak** [comment]
justt replace these files in clover folder 
[FILES.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2825814/FILES.zip)


make sure you have vanilla applehda installed to work with AppleALC

**Comment by rajverma1985** [comment]
so the aml goes inside the patched folder and rest remains same? and just to make sure where can i download the vanilla appleHDA from?

**Comment by rajverma1985** [comment]
> 
> 
> justt replace these files in clover folder
> [FILES.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2825814/FILES.zip)
> 
> make sure you have vanilla applehda installed to work with AppleALC

so i tried the FILES.zip but did not work out. Still no Audio. i also tried running alc fix after copying those files over, but no go :(

**Comment by insanelydeepak** [comment]
install this and USE SSDT inside
remove appleALC 
[FILES.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2826494/FILES.zip)

**Comment by insanelydeepak** [comment]
change config to 14 

first remove AppleALC and run kextutility drag appleHDA.kext on it and wait till finish 

restart and see if any change 

use below link to generate debug files 
https://github.com/black-dragon74/OSX-Debug

**Comment by rajverma1985** [comment]
no audio, attaching debug.

present situation:

-- no ALC , installed HDA, changed id to 14.
[debug_5729.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2826774/debug_5729.zip)

**Comment by insanelydeepak** [comment]
replace this folder in clover/ACPI/patched 

you don't need dsl files there only aml get used and if you have 2 or 3 aml with old or any other name all will be used , which already created a mess 

try this and report with debug again 

[patched.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2826830/patched.zip)

**Comment by rajverma1985** [comment]
> replace this folder in clover/ACPI/patched
> 
> you don't need dsl files there only aml get used and if you have 2 or 3 aml with old or any other name all will be used , which already created a mess
> 
> try this and report with debug again
> 
> [patched.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2826830/patched.zip)

so basically replace the entire patched folder with this only aml?? or keep everything in patched folder?

**Comment by rajverma1985** [comment]
you were right I don't need all those files in there. replaced and here is the latest debug.
[debug_18320.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2826942/debug_18320.zip)

**Comment by insanelydeepak** [comment]
try this config.plist
[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2826959/config.plist.zip)

**Comment by rajverma1985** [comment]
doesn't work. :(

**Comment by rajverma1985** [comment]
Latest Debug after changing the config file.
[debug_1522.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2826990/debug_1522.zip)

**Comment by insanelydeepak** [comment]
issue is layout id is not injecting something is messing around still try this config.plist 

also remove appleHDA from clover folder 

[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2827299/config.plist.zip)

**Comment by rajverma1985** [comment]
if I take out HDA then there is no other audio kext!! not even alc??

Also, how did you figure out layout id is not getting injecting. if you can share the steps that you do to check the debug files it will be great. I will try this config and share the latest debug in case it doesn't work. Thanks again

**Comment by insanelydeepak** [comment]
> if I take out HDA then there is no other audio kext!! not even alc??

you have to install HDA in s/l/e using kext utility 

> Also, how did you figure out layout id is not getting injecting.

IORegistery , just read it

**Comment by rajverma1985** [comment]
AWESOME!!! that worked yay...... Thanks a lot bro. appreciate it. Now I just want to know how to look at this stuff a little more. I want to contribute towards Hackintosh projects as well.

And THANKS again.

removing the HDA, adding new config file did it. now I'm not sure if its just the config file or HDA. What change did you do in the config file?

**Comment by insanelydeepak** [comment]
great news , actually config files were pretty messed up , there were many stuff aren't required , for reading IORegistery you need IORegistery Explorer , for other logs there are already you have to check kext is loaded or not 


now you can use AppleALC too , you need to change 14 to 13 and replace patched applehda with vanila (non patched )

**Comment by rajverma1985** [comment]
> > Now I just want to know how to look at this stuff a little more. I want to contribute towards Hackintosh projects as well.
> 
> first fix your system there is still mess around and then you understand many stuff will help you better
> there are forums below you can grab too many things
> http://forum.osxlatitude.com and
> https://www.insanelymac.com/forum/
> 
> Good luck enjoy good sound 👍

So what else are the things you think are messed up and needs to be straightened ??

**Comment by rajverma1985** [comment]
> great news , actually config files were pretty messed up , there were many stuff aren't required , for reading IORegistery you need IORegistery Explorer , for other logs there are already you have to check kext is loaded or not
> 
> now you can use AppleALC too , you need to change 14 to 13 and replace patched applehda with vanila (non patched )

These 2 kexts are to be installed in clover or s/l/e ??

**Comment by insanelydeepak** [comment]
AppleALC can be used from both clover or s/l/e , better to use clover 

AppleHDA is system kext so it must be in S/L/E , it has dependencies to other kext so i can't work from outside

**Comment by rajverma1985** [comment]
> AppleALC can be used from both clover or s/l/e , better to use clover
> 
> AppleHDA is system kext so it must be in S/L/E , it has dependencies to other kext so i can't work from outside

Thanks again for your reply. Do you mind sharing the correct vanilla kexts? cos I do not want to mess up the system. I have been trying to get the audio working from last 2 months.

Also, if I understand you correctly now I can go ahead and change the id to 13 and put vanilla ALC in clover and override the HDA kext that is already there in s/l/e with the vanilla HDA kext.

PS: please share both the vanilla kexts if you can. I google's and found multiple of them but just a little skeptical and don't want to mess up the system.

**Comment by insanelydeepak** [comment]
use this one 
[AppleHDA.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.14/files/2828332/AppleHDA.kext.zip)

**Comment by insanelydeepak** [comment]
> Also, please please mention what you think is messed up as well so that I can try and rectify that.

there is SSDT injecting your graphics properties , same in config.plist too , why two side when one is enough , i found layout id was injected multiple times in config.plist and ssdt which is unneccessary 

actually main reason is you used someone else files , he/she might need some specific patches and changes which your system doesn't , you have remove all unnecessary things and use minimal as possible  so next time software update or OS Upgrade couldn't affect you so much 

i remember fakePCI kext aren't required much you can use lilu and it's plugin is enough 

that's all , start using system most of time you will know what is wrong and when you fix it you will learn enough

**Comment by insanelydeepak** [comment]
https://osxlatitude.com/forums/topic/11183-acer-predator-helios-300-mojave/ 

took above link as example , recently i fixed this for my friend , each and everything is working
do same for your system that's all

**Comment by rajverma1985** [comment]
> https://osxlatitude.com/forums/topic/11183-acer-predator-helios-300-mojave/
> 
> took above link as example , recently i fixed this for my friend , each and everything is working
> do same for your system that's all

I tried doing the install with the above and minimal kexts but it doesn't even boot. it gets stuck while trying to boot from the USB. How do you debug that? Tried F2 but did not get much info in the preboot.log.

How do you find out what's causing the issue and what about the aml file, how do i create one?

**Comment by insanelydeepak** [comment]
> tried doing the install with the above and minimal kexts but it doesn't even boot. it gets stuck while trying to boot from the USB. How do you debug that? Tried F2 but did not get much info in the preboot.log.
> 
> How do you find out what's causing the issue and what about the aml file, how do i create one?

always boot in verbsoe -v and took screenshot of where it stuck or panic , better to create post at osxlatitude and let other to help you
